/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RepurchasesRouteImport } from './routes/repurchases'
import { Route as PipelineRouteImport } from './routes/pipeline'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as InactiveRouteImport } from './routes/inactive'
import { Route as CustomersRouteImport } from './routes/customers'
import { Route as CampaignsRouteImport } from './routes/campaigns'
import { Route as AuthConfirmationRouteImport } from './routes/auth-confirmation'
import { Route as IndexRouteImport } from './routes/index'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RepurchasesRoute = RepurchasesRouteImport.update({
  id: '/repurchases',
  path: '/repurchases',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelineRoute = PipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const InactiveRoute = InactiveRouteImport.update({
  id: '/inactive',
  path: '/inactive',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersRoute = CustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsRoute = CampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthConfirmationRoute = AuthConfirmationRouteImport.update({
  id: '/auth-confirmation',
  path: '/auth-confirmation',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth-confirmation': typeof AuthConfirmationRoute
  '/campaigns': typeof CampaignsRoute
  '/customers': typeof CustomersRoute
  '/inactive': typeof InactiveRoute
  '/inbox': typeof InboxRoute
  '/login': typeof LoginRoute
  '/pipeline': typeof PipelineRoute
  '/repurchases': typeof RepurchasesRoute
  '/settings': typeof SettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth-confirmation': typeof AuthConfirmationRoute
  '/campaigns': typeof CampaignsRoute
  '/customers': typeof CustomersRoute
  '/inactive': typeof InactiveRoute
  '/inbox': typeof InboxRoute
  '/login': typeof LoginRoute
  '/pipeline': typeof PipelineRoute
  '/repurchases': typeof RepurchasesRoute
  '/settings': typeof SettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth-confirmation': typeof AuthConfirmationRoute
  '/campaigns': typeof CampaignsRoute
  '/customers': typeof CustomersRoute
  '/inactive': typeof InactiveRoute
  '/inbox': typeof InboxRoute
  '/login': typeof LoginRoute
  '/pipeline': typeof PipelineRoute
  '/repurchases': typeof RepurchasesRoute
  '/settings': typeof SettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth-confirmation'
    | '/campaigns'
    | '/customers'
    | '/inactive'
    | '/inbox'
    | '/login'
    | '/pipeline'
    | '/repurchases'
    | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth-confirmation'
    | '/campaigns'
    | '/customers'
    | '/inactive'
    | '/inbox'
    | '/login'
    | '/pipeline'
    | '/repurchases'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/auth-confirmation'
    | '/campaigns'
    | '/customers'
    | '/inactive'
    | '/inbox'
    | '/login'
    | '/pipeline'
    | '/repurchases'
    | '/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthConfirmationRoute: typeof AuthConfirmationRoute
  CampaignsRoute: typeof CampaignsRoute
  CustomersRoute: typeof CustomersRoute
  InactiveRoute: typeof InactiveRoute
  InboxRoute: typeof InboxRoute
  LoginRoute: typeof LoginRoute
  PipelineRoute: typeof PipelineRoute
  RepurchasesRoute: typeof RepurchasesRoute
  SettingsRoute: typeof SettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repurchases': {
      id: '/repurchases'
      path: '/repurchases'
      fullPath: '/repurchases'
      preLoaderRoute: typeof RepurchasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipeline': {
      id: '/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof PipelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inactive': {
      id: '/inactive'
      path: '/inactive'
      fullPath: '/inactive'
      preLoaderRoute: typeof InactiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers': {
      id: '/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns': {
      id: '/campaigns'
      path: '/campaigns'
      fullPath: '/campaigns'
      preLoaderRoute: typeof CampaignsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth-confirmation': {
      id: '/auth-confirmation'
      path: '/auth-confirmation'
      fullPath: '/auth-confirmation'
      preLoaderRoute: typeof AuthConfirmationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthConfirmationRoute: AuthConfirmationRoute,
  CampaignsRoute: CampaignsRoute,
  CustomersRoute: CustomersRoute,
  InactiveRoute: InactiveRoute,
  InboxRoute: InboxRoute,
  LoginRoute: LoginRoute,
  PipelineRoute: PipelineRoute,
  RepurchasesRoute: RepurchasesRoute,
  SettingsRoute: SettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
