// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hqoybksxdudrpeuryoln.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhxb3lia3N4ZHVkcnBldXJ5b2xuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzkwMTcwNTcsImV4cCI6MjA5NDU5MzA1N30.GyNSjQhz0415hM7TPRyv0GnnD46vsQwt6AvoU-5AdVM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});